# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('created', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
